### ISSUE TITLE
Update Self-Hosted docs for 0.10.0

### ISSUE THREAD

**Issue by geropl** [gitpod-io/website#745]
Engineering issue: https://github.com/gitpod-io/gitpod/issues/4710

ToDos:
Dumping my personal notes here, in hope this might help whoever works on this:
 - [x] docs:
   - [x] "Configure Ingress": cerbot: copy'n'paste is broken
   - [x] replace "find -exec copy broken: "find $WORKDIR/config/live -name "*.pem" -exec cp {} secrets/https-certificates \;" with
     - cp $WORKDIR/config/live/fullchain.pem secrets/https-certificates/tls.crt
     - cp $WORKDIR/config/live/privkey.pem secrets/https-certificates/tls.key
   - [x] troubleshooting:
     - [x] container runtime config for k3s:
        ```
        containerRuntime:
        containerd:
            socket: /var/run/k3s/containerd/containerd.sock
        nodeRoots:
            - /var/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io
        ```
     - [x] make visible in the navigation
   - [x] migration guide:
     - [x] make visible in navigation
     - [x] 0.9.0 -> 0.10.0
       - mv secrets/https-certificates/fullchain.pem secrets/https-certificates/tls.crt
       - mv secrets/https-certificates/privkey.pem secrets/https-certificates/tls.key
