### ISSUE TITLE
[Start Task Example] Await Docker Container to start

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#852]
I'm having the following scenario

```yml
tasks:
  - name: Install npm depdencies
    init: |
      npm i -g npm
      npm install
    command: npm run start:dev
  - name: Setup Docker
    command: docker-compose up
```
I need to wait until the docker-container started with `docker-compose up` until the command `npm run start:dev` can be executed. Is this possible with `gp sync-await` and `gp sync-done` as the docker-compose will be a process that doesnt terminate.

Thanks in Advance

Greetz

Cahllagerfeld
